// Code generated by apolon. DO NOT EDIT.
package main

import "github.com/jkeresman01/apolon/apolon-shared"

// PatientFields provides typed field accessors for Patient queries
var PatientFields = struct {
	ID   shared.IntField
	Name shared.StringField
	Age  shared.IntField
}{
	ID:   shared.IntField{BaseField: shared.BaseField{Table: "patients", Column: "id"}},
	Name: shared.StringField{BaseField: shared.BaseField{Table: "patients", Column: "name"}},
	Age:  shared.IntField{BaseField: shared.BaseField{Table: "patients", Column: "age"}},
}

// P is a short alias for PatientFields
var P = PatientFields
