package generator

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// CodeGen handles code generation from parsed models
type CodeGen struct {
	outputDir string
}

// NewCodeGen creates a new code generator for the given output directory
func NewCodeGen(outputDir string) *CodeGen {
	return &CodeGen{outputDir: outputDir}
}

// Generate generates the *_fields.go file for the given models
func (c *CodeGen) Generate(sourceFile string, models []ModelInfo) error {
	if len(models) == 0 {
		return nil
	}

	baseName := filepath.Base(sourceFile)
	baseName = strings.TrimSuffix(baseName, ".go")
	outputFile := filepath.Join(c.outputDir, baseName+"_fields.go")

	var buf bytes.Buffer
	if err := fieldsTemplate.Execute(&buf, models); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	if err := os.WriteFile(outputFile, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	fmt.Printf("Generated %s\n", outputFile)
	return nil
}

var fieldsTemplate = template.Must(template.New("fields").Funcs(template.FuncMap{
	"firstLetter": func(s string) string {
		if len(s) == 0 {
			return ""
		}
		return strings.ToUpper(string(s[0]))
	},
}).Parse(`// Code generated by apolon. DO NOT EDIT.
package {{ (index . 0).Package }}

import "github.com/jkeresman01/apolon/apolon-shared"
{{ range $model := . }}
// {{ $model.Name }}Fields provides typed field accessors for {{ $model.Name }} queries
var {{ $model.Name }}Fields = struct {
{{- range $model.Fields }}
	{{ .Name }} shared.{{ .FieldType }}
{{- end }}
}{
{{- range $model.Fields }}
	{{ .Name }}: shared.{{ .FieldType }}{BaseField: shared.BaseField{Table: "{{ $model.Table }}", Column: "{{ .Column }}"}},
{{- end }}
}

// {{ firstLetter $model.Name }} is a short alias for {{ $model.Name }}Fields
var {{ firstLetter $model.Name }} = {{ $model.Name }}Fields
{{ end }}`))
